In [2]:
import pandas as pd
from datetime import datetime
import soccerdata as sd
import os,sys,requests
import sql_connector as SQL
import config

C:\Users\Hp\AppData\Local\Temp\ipykernel_3260\322462531.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

[03/28/24 05:07:20] INFO     Custom team name replacements loaded from                                _config.py:82
                             C:\Users\Hp\soccerdata\config\teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    _config.py:204
                             C:\Users\Hp\soccerdata\config\league_dict.json.

In [3]:
matches = SQL.execute_select_query("select * from match_schedule")

In [4]:
matches = pd.DataFrame(matches)

In [5]:
matches.head(2)

,id,competition,season,stage,date,home_team,away_team,score,whoscored_id,whoscored_url,fbref_id,fbref_url,fotmob_id,fotmob_url,read_status
0,42740,ENG-Premier League,17-18,nan,2017-08-11,Arsenal,Leicester,4–3,1190170.0,https://1xbet.whoscored.com/Matches/1190174/Li...,e3c3ddf0,/en/matches/e3c3ddf0/Arsenal-Leicester-City-Au...,2522743,/matches/leicester-city-vs-arsenal/2op49y#2522743,NotStarted
1,42741,ENG-Premier League,17-18,nan,2017-08-12,Watford,Liverpool,3–3,1190180.0,https://1xbet.whoscored.com/Matches/1190182/Li...,60f6cc1d,/en/matches/60f6cc1d/Watford-Liverpool-August-...,2522751,/matches/liverpool-vs-watford/2tj4y7#2522751,NotStarted

In [6]:
def check_WSurl_contains_id(row):
    if str(int(row['whoscored_id'])) in str(row['whoscored_url']):
        return True
    else:
        return False
def check_FBurl_contains_id(row):
    if str(row['fbref_id']) in str(row['fbref_url']):
        return True
    else:
        return False
                
def check_FMurl_contains_id(row):
    if str(row['fotmob_id']) in str(row['fotmob_id']):
        return True
    else:
        return False

In [7]:
df = pd.DataFrame()
# Apply the function to each row and create a new column 'contains_id'
df= matches[['id','competition','season','stage','date','home_team','away_team','score','whoscored_id','whoscored_url']]
df['WS_contains_id'] = matches.apply(check_WSurl_contains_id, axis=1)
df['FB_contains_id'] = matches.apply(check_FBurl_contains_id, axis=1)
df['FM_contains_id'] = matches.apply(check_FMurl_contains_id, axis=1)
df['whoscored_id'] = df['whoscored_id'].astype(int)
# Display the DataFrame with the new column
df

C:\Users\Hp\AppData\Local\Temp\ipykernel_3260\2148059069.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['WS_contains_id'] = matches.apply(check_WSurl_contains_id, axis=1)
C:\Users\Hp\AppData\Local\Temp\ipykernel_3260\2148059069.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FB_contains_id'] = matches.apply(check_FBurl_contains_id, axis=1)
C:\Users\Hp\AppData\Local\Temp\ipykernel_3260\2148059069.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FM_contains_id'] = matches.apply(check_FMurl_contains_id, axis=1)
C:\Users\Hp\AppData\Local\Temp\ipykernel_3260\2148059069.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['whoscored_id'] = df['whoscored_id'].astype(int)

,id,competition,season,stage,date,home_team,away_team,score,whoscored_id,whoscored_url,WS_contains_id,FB_contains_id,FM_contains_id
0,42740,ENG-Premier League,17-18,nan,2017-08-11,Arsenal,Leicester,4–3,1190170,https://1xbet.whoscored.com/Matches/1190174/Li...,False,True,True
1,42741,ENG-Premier League,17-18,nan,2017-08-12,Watford,Liverpool,3–3,1190180,https://1xbet.whoscored.com/Matches/1190182/Li...,False,True,True
2,42742,ENG-Premier League,17-18,nan,2017-08-12,Chelsea,Burnley,2–3,1190180,https://1xbet.whoscored.com/Matches/1190176/Li...,False,True,True
3,42743,ENG-Premier League,17-18,nan,2017-08-12,Crystal Palace,Huddersfield,0–3,1190180,https://1xbet.whoscored.com/Matches/1190177/Li...,False,True,True
4,42744,ENG-Premier League,17-18,nan,2017-08-12,Everton,Stoke,1–0,1190180,https://1xbet.whoscored.com/Matches/1190178/Li...,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20364,63105,UEL,23-24,Europa League Final Stage,2024-03-14,Atalanta,Sporting CP,2–1,1805550,https://1xbet.whoscored.com/Matches/1805546/Li...,False,True,True
20365,63106,UEL,23-24,Europa League Final Stage,2024-03-14,Bayer Leverkusen,Qarabag FK,3–2,1805550,https://1xbet.whoscored.com/Matches/1805550/Li...,True,True,True
20366,63107,UEL,23-24,Europa League Final Stage,2024-03-14,Brighton,Roma,1–0,1805540,https://1xbet.whoscored.com/Matches/1805540/Li...,True,True,True
20367,63108,UEL,23-24,Europa League Final Stage,2024-03-14,Liverpool,Sparta Prague,6–1,1805540,https://1xbet.whoscored.com/Matches/1805536/Li...,False,True,True
20368,63109,Primeira_Liga,23-24,None,2024-03-17,Chaves,Vitoria de Guimaraes,1–2,1748590,https://1xbet.whoscored.com/Matches/1748587/Li...,False,True,True

In [8]:
df['WS_contains_id'].value_counts(),\
df['FB_contains_id'].value_counts(),\
df['FM_contains_id'].value_counts()

(WS_contains_id
 False    18324
 True      2045
 Name: count, dtype: int64,
 FB_contains_id
 True    20369
 Name: count, dtype: int64,
 FM_contains_id
 True    20369
 Name: count, dtype: int64)

In [9]:
def extract_id_from_url(row):
    # Define the regex pattern to match the ID in the URL
    pattern = r'/Matches/(\d+)/'
    import re
    # Search for the pattern in the URL
    match = re.search(pattern, row['whoscored_url'])

    if match:
        # Extract the ID from the matched group
        return match.group(1)
    else:
        # If no match found, return None
        return None

In [10]:
df['correct_ws_id'] = df.apply(extract_id_from_url,axis=1)

C:\Users\Hp\AppData\Local\Temp\ipykernel_3260\3817345907.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['correct_ws_id'] = df.apply(extract_id_from_url,axis=1)

In [15]:
for ws_id,id in zip(df['whoscored_id'],df['id']):
    print(ws_id,id)
    r = SQL.execute_select_query("select * from match_schedule where whoscored_id = '{}' and id = '{}'".format(ws_id,id))
    if len(r) == 1:
        print(r)
        # SQL.execute_update_query("update match_schedule set whoscored_id = '{}' where id = '{}'".format(ws_id,id))
    break

1190170 42740

DatabaseError: 1040 (HY000): Too many connections

In [12]:
df

,id,competition,season,stage,date,home_team,away_team,score,whoscored_id,whoscored_url,WS_contains_id,FB_contains_id,FM_contains_id,correct_ws_id
0,42740,ENG-Premier League,17-18,nan,2017-08-11,Arsenal,Leicester,4–3,1190170,https://1xbet.whoscored.com/Matches/1190174/Li...,False,True,True,1190174
1,42741,ENG-Premier League,17-18,nan,2017-08-12,Watford,Liverpool,3–3,1190180,https://1xbet.whoscored.com/Matches/1190182/Li...,False,True,True,1190182
2,42742,ENG-Premier League,17-18,nan,2017-08-12,Chelsea,Burnley,2–3,1190180,https://1xbet.whoscored.com/Matches/1190176/Li...,False,True,True,1190176
3,42743,ENG-Premier League,17-18,nan,2017-08-12,Crystal Palace,Huddersfield,0–3,1190180,https://1xbet.whoscored.com/Matches/1190177/Li...,False,True,True,1190177
4,42744,ENG-Premier League,17-18,nan,2017-08-12,Everton,Stoke,1–0,1190180,https://1xbet.whoscored.com/Matches/1190178/Li...,False,True,True,1190178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20364,63105,UEL,23-24,Europa League Final Stage,2024-03-14,Atalanta,Sporting CP,2–1,1805550,https://1xbet.whoscored.com/Matches/1805546/Li...,False,True,True,1805546
20365,63106,UEL,23-24,Europa League Final Stage,2024-03-14,Bayer Leverkusen,Qarabag FK,3–2,1805550,https://1xbet.whoscored.com/Matches/1805550/Li...,True,True,True,1805550
20366,63107,UEL,23-24,Europa League Final Stage,2024-03-14,Brighton,Roma,1–0,1805540,https://1xbet.whoscored.com/Matches/1805540/Li...,True,True,True,1805540
20367,63108,UEL,23-24,Europa League Final Stage,2024-03-14,Liverpool,Sparta Prague,6–1,1805540,https://1xbet.whoscored.com/Matches/1805536/Li...,False,True,True,1805536
20368,63109,Primeira_Liga,23-24,None,2024-03-17,Chaves,Vitoria de Guimaraes,1–2,1748590,https://1xbet.whoscored.com/Matches/1748587/Li...,False,True,True,1748587